// ============================================================================
// Part of the site content config (split from siteConfig.js).
// Re-exported by siteConfig.js — import from "../config/siteConfig" as usual.
// ============================================================================

// ─── 🎪 Events ──────────────────────────────────────────────────────────────
// Categories available: "Welcome", "Welfare", "Cultural", "Sports", "Academic",
// "Collaboration", "Workshop", "Community" (add new ones by just using them —
// filter buttons auto-generate)
//
// Status values (drive the colored badge + registration block on detail page):
//   "upcoming"  — announced, registration not open yet
//   "open"      — registration currently open (needs registrationLink)
//   "closed"    — registration period over, event hasn't happened yet
//   "completed" — event happened recently
//   "archived"  — event happened a while ago (shows in Past Events > by year)
//
// To add a new event, copy-paste this template:
// {
//   id: "kebab-case-slug-year",          ← unique, used in the /events/:id URL
//   title: "Event Name",
//   date: "YYYY-MM-DD",                  ← ISO format, used for sorting/grouping
//   dateDisplay: "DD Mon YYYY",           ← human-readable, used in the UI
//   time: "10:00 AM",
//   venue: "Venue name",
//   category: "Welcome",
//   status: "upcoming",
//   poster: null,                        ← image path, or null for placeholder
//   description: "Full description for the detail page.",
//   excerpt: "Short one-liner for cards.",
//   registrationLink: null,              ← set when status is "open"/"closed"
//   registrationDeadline: null,          ← "YYYY-MM-DD" or null
//   photos: null,                        ← Drive/album link, or null
//   recapArticle: null,                  ← URL to a recap article, or null
//   sponsors: [],                        ← array of names, or empty
//   organizerDept: "Events",
//   featured: false,                     ← true to highlight on the homepage
// },
//
export const EVENTS = [
  {
    id: "rantau-heist-2026",
    title: "Rantau Heist",
    date: "2026-03-14",
    dateDisplay: "14 Mar 2026",
    time: "10:00 AM",
    venue: "Sunway Lagoon, Bandar Sunway",
    category: "Welcome",
    status: "completed",
    poster: null,
    description: {
      en: "A thrilling welcome event where new intakes embarked on a dangerous mission to retrieve fortune through teamwork, resilience, and a willingness to betray even their closest teammates. Teams raced across themed checkpoints solving puzzles, completing physical challenges, and forming alliances (or rivalries) that carried on long after the heist ended.",
      id: "Acara penyambutan seru tempat mahasiswa baru menjalankan misi berbahaya untuk merebut harta melalui kerja sama tim, ketangguhan, dan kesediaan untuk mengkhianati bahkan rekan terdekat. Tim berlomba melewati pos-pos bertema sambil memecahkan teka-teki, menyelesaikan tantangan fisik, dan membentuk aliansi (atau rivalitas) yang berlanjut lama setelah heist berakhir.",
    },
    excerpt: {
      en: "New intakes embark on a dangerous mission to retrieve fortune through teamwork, resilience, and a willingness to betray even their closest teammates.",
      id: "Mahasiswa baru menjalankan misi berbahaya untuk merebut harta melalui kerja sama tim, ketangguhan, dan kesediaan mengkhianati bahkan rekan terdekat.",
    },
    registrationLink: null,
    registrationDeadline: null,
    photos: "https://drive.google.com/drive/folders/1qN7mzfjQQK42_1FI1HDEgt2S9R0cQd_L",
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "survival-night-2025",
    title: "Survival Night: Game Over",
    date: "2025-11-01",
    dateDisplay: "1 Nov 2025",
    time: "7:00 PM",
    venue: "Monash University Malaysia, Sunway Campus",
    category: "Welfare",
    status: "archived",
    poster: null,
    description: {
      en: "The ultimate test of courage, strategy, and endurance. In a secret location cloaked in mystery, alliances formed, tensions rose, and only the sharpest outlasted the game. A night of immersive challenges designed to bring the community closer through shared (and slightly stressful) memories.",
      id: "Ujian pamungkas keberanian, strategi, dan ketahanan. Di lokasi rahasia yang penuh misteri, aliansi terbentuk, ketegangan memuncak, dan hanya yang paling jeli yang bertahan sampai akhir. Malam penuh tantangan imersif yang dirancang untuk mendekatkan komunitas melalui kenangan bersama (yang sedikit menegangkan).",
    },
    excerpt: {
      en: "The ultimate test of courage, strategy, and endurance — alliances form, tensions rise, and only the sharpest outlast the game.",
      id: "Ujian pamungkas keberanian, strategi, dan ketahanan — aliansi terbentuk, ketegangan memuncak, dan hanya yang paling jeli yang bertahan.",
    },
    registrationLink: null,
    registrationDeadline: null,
    photos: "https://drive.google.com/drive/folders/1ZN06XnGKbzB72ouGJ42sQMj7jKx6fX9e",
    recapArticle: null,
    sponsors: [],
    organizerDept: "Welfare",
    featured: false,
  },
  {
    id: "independence-day-2025",
    title: "Independence Day 2025",
    date: "2025-08-17",
    dateDisplay: "17 Aug 2025",
    time: "5:00 PM",
    venue: "KDU Penthouse Hall, Sunway",
    category: "Cultural",
    status: "archived",
    poster: null,
    description: {
      en: "Celebrating Indonesia's independence with cultural performances, traditional games, and a community gathering that brought everyone together. The evening featured a flag ceremony, regional dance showcases, and a potluck of Indonesian dishes cooked by members themselves.",
      id: "Merayakan kemerdekaan Indonesia dengan pertunjukan budaya, permainan tradisional, dan kebersamaan yang mempersatukan semua orang. Malam itu menampilkan upacara bendera, tarian daerah, dan potluck hidangan Indonesia yang dimasak sendiri oleh para anggota.",
    },
    excerpt: {
      en: "Celebrating Indonesia's independence with cultural performances, traditional games, and a community gathering.",
      id: "Merayakan kemerdekaan Indonesia dengan pertunjukan budaya, permainan tradisional, dan kebersamaan komunitas.",
    },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "one-world-2026",
    title: "One World: Indonesia Hand in Hand",
    date: "2026-05-09",
    dateDisplay: "9 May 2026",
    time: "9:00 AM",
    venue: "Monash Sports Centre, Sunway",
    category: "Sports",
    status: "completed",
    poster: null,
    description: {
      en: "MUISS OneWorld brought students together representing their country in four different sports — a wonderful celebration of unity through competition. PPI Monash fielded teams across futsal, badminton, basketball, and tug-of-war, finishing as one of the top three contingents overall.",
      id: "MUISS OneWorld mempertemukan mahasiswa yang mewakili negaranya dalam empat cabang olahraga berbeda — perayaan persatuan yang indah melalui kompetisi. PPI Monash menurunkan tim di futsal, bulu tangkis, basket, dan tarik tambang, dan finis sebagai salah satu dari tiga kontingen terbaik secara keseluruhan.",
    },
    excerpt: {
      en: "MUISS OneWorld brought students together representing their country in four different sports — a wonderful celebration of unity through competition.",
      id: "MUISS OneWorld mempertemukan mahasiswa yang mewakili negaranya dalam empat cabang olahraga — perayaan persatuan yang indah melalui kompetisi.",
    },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: "https://ppimonashmalaysia.com/articles/one-world-2026/",
    sponsors: [],
    organizerDept: "External Relations",
    featured: false,
  },
  {
    id: "mini-welpar-2026",
    title: "Mini Welpar",
    date: "2026-08-08",
    dateDisplay: "8 Aug 2026",
    time: null,
    venue: "To be announced",
    category: "Welcome",
    status: "upcoming",
    poster: null,
    description: {
      en: "Part of Kabinet Eunoia's Semester 2 2026 program — full details to be announced.",
      id: "Bagian dari program Kabinet Eunoia Semester 2 2026 — detail lengkap akan diumumkan.",
    },
    excerpt: { en: "Details to be announced.", id: "Detail akan diumumkan." },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "independence-day-2026",
    title: "Independence Day",
    date: "2026-08-15",
    dateDisplay: "15 Aug 2026",
    time: null,
    venue: "To be announced",
    category: "Cultural",
    status: "upcoming",
    poster: null,
    description: {
      en: "Part of Kabinet Eunoia's Semester 2 2026 program — full details to be announced.",
      id: "Bagian dari program Kabinet Eunoia Semester 2 2026 — detail lengkap akan diumumkan.",
    },
    excerpt: { en: "Details to be announced.", id: "Detail akan diumumkan." },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: true,
  },
  {
    id: "independence-day-charity-2026",
    title: "Independence Day Charity Event",
    date: "2026-08-17",
    dateDisplay: "17–19 Aug 2026",
    time: null,
    venue: "To be announced",
    category: "Community",
    status: "upcoming",
    poster: null,
    description: {
      en: "Part of Kabinet Eunoia's Semester 2 2026 program — full details to be announced.",
      id: "Bagian dari program Kabinet Eunoia Semester 2 2026 — detail lengkap akan diumumkan.",
    },
    excerpt: { en: "Details to be announced.", id: "Detail akan diumumkan." },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "mcn-2026",
    title: "MCN",
    date: "2026-09-15",
    dateDisplay: "Tentative",
    time: null,
    venue: "To be announced",
    category: "Cultural",
    status: "upcoming",
    poster: null,
    description: {
      en: "Part of Kabinet Eunoia's Semester 2 2026 program — date tentative, details to be announced.",
      id: "Bagian dari program Kabinet Eunoia Semester 2 2026 — tanggal tentatif, detail akan diumumkan.",
    },
    excerpt: { en: "Date tentative — details to be announced.", id: "Tanggal tentatif — detail akan diumumkan." },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "welpar-october-2026",
    title: "Welpar October",
    date: "2026-10-31",
    dateDisplay: "31 Oct 2026",
    time: null,
    venue: "To be announced",
    category: "Welcome",
    status: "upcoming",
    poster: null,
    description: {
      en: "Part of Kabinet Eunoia's Semester 2 2026 program — full details to be announced.",
      id: "Bagian dari program Kabinet Eunoia Semester 2 2026 — detail lengkap akan diumumkan.",
    },
    excerpt: { en: "Details to be announced.", id: "Detail akan diumumkan." },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "makeun-2026",
    title: "Makeun",
    date: "2026-11-30",
    dateDisplay: "Monthly",
    time: null,
    venue: "To be announced",
    category: "Community",
    status: "upcoming",
    poster: null,
    description: {
      en: "A monthly community get-together — part of Kabinet Eunoia's Semester 2 2026 program. Details to be announced.",
      id: "Kumpul komunitas bulanan — bagian dari program Kabinet Eunoia Semester 2 2026. Detail akan diumumkan.",
    },
    excerpt: { en: "A monthly community get-together.", id: "Kumpul komunitas bulanan." },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "leadership-summit-2024",
    title: "PPI Leadership Summit",
    date: "2024-09-20",
    dateDisplay: "20 Sep 2024",
    time: "9:00 AM",
    venue: "Monash University Malaysia, Function Room 2",
    category: "Academic",
    status: "archived",
    poster: null,
    description: {
      en: "A half-day workshop for incoming and outgoing committee members on event planning, budgeting, and community leadership, capped off with a handover ceremony between generations of PPI leadership.",
      id: "Lokakarya setengah hari bagi pengurus baru dan lama tentang perencanaan acara, penganggaran, dan kepemimpinan komunitas, ditutup dengan serah terima antargenerasi kepengurusan PPI.",
    },
    excerpt: {
      en: "A half-day workshop for incoming and outgoing committee members on event planning, budgeting, and community leadership.",
      id: "Lokakarya setengah hari bagi pengurus baru dan lama tentang perencanaan acara, penganggaran, dan kepemimpinan komunitas.",
    },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: null,
    sponsors: [],
    organizerDept: "Executive",
    featured: false,
  },
  {
    id: "merdeka-run-2024",
    title: "Merdeka Charity Run",
    date: "2024-08-18",
    dateDisplay: "18 Aug 2024",
    time: "7:00 AM",
    venue: "Sunway Lagoon Boulevard",
    category: "Community",
    status: "archived",
    poster: null,
    description: {
      en: "A 5km community fun run held in conjunction with Indonesian and Malaysian independence celebrations, raising funds for a local orphanage in Subang Jaya. Open to students, alumni, and the wider Sunway community.",
      id: "Lari santai komunitas sejauh 5km yang digelar bertepatan dengan perayaan kemerdekaan Indonesia dan Malaysia, untuk menggalang dana bagi panti asuhan di Subang Jaya. Terbuka untuk mahasiswa, alumni, dan komunitas Sunway yang lebih luas.",
    },
    excerpt: {
      en: "A 5km community fun run raising funds for a local orphanage, held in conjunction with Indonesian and Malaysian independence celebrations.",
      id: "Lari santai komunitas 5km untuk menggalang dana bagi panti asuhan, digelar bertepatan dengan perayaan kemerdekaan Indonesia dan Malaysia.",
    },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: null,
    sponsors: ["Sunway Pyramid Mall"],
    organizerDept: "Welfare",
    featured: false,
  },
];
