// ============================================================================
// Part of the site content config (split from siteConfig.js).
// Re-exported by siteConfig.js — import from "../config/siteConfig" as usual.
// ============================================================================

// ─── 🎪 Events ──────────────────────────────────────────────────────────────
// Categories available: "Welcome", "Welfare", "Cultural", "Sports", "Academic",
// "Collaboration", "Workshop", "Community" (add new ones by just using them —
// filter buttons auto-generate)
//
// Status values (drive the colored badge + registration block on detail page):
//   "upcoming"  — announced, registration not open yet
//   "open"      — registration currently open (needs registrationLink)
//   "closed"    — registration period over, event hasn't happened yet
//   "completed" — event happened recently
//   "archived"  — event happened a while ago (shows in Past Events > by year)
//
// To add a new event, copy-paste this template:
// {
//   id: "kebab-case-slug-year",          ← unique, used in the /events/:id URL
//   title: "Event Name",
//   date: "YYYY-MM-DD",                  ← ISO format, used for sorting/grouping
//   dateDisplay: "DD Mon YYYY",           ← human-readable, used in the UI
//   time: "10:00 AM",
//   venue: "Venue name",
//   category: "Welcome",
//   status: "upcoming",
//   poster: null,                        ← image path, or null for placeholder
//   description: "Full description for the detail page.",
//   excerpt: "Short one-liner for cards.",
//   registrationLink: null,              ← set when status is "open"/"closed"
//   registrationDeadline: null,          ← "YYYY-MM-DD" or null
//   photos: null,                        ← Drive/album link, or null
//   recapArticle: null,                  ← URL to a recap article, or null
//   sponsors: [],                        ← array of names, or empty
//   organizerDept: "Events",
//   featured: false,                     ← true to highlight on the homepage
// },
//
export const EVENTS = [
  {
    id: "rantau-heist-2026",
    title: "Rantau Heist",
    date: "2026-03-14",
    dateDisplay: "14 Mar 2026",
    time: "3:00 PM",
    venue: "Monash University Malaysia, Sunway Campus",
    category: "Welcome",
    status: "completed",
    poster: "/assets/photos/event_cover/rantauheist.png",
    description: {
      en: "The price of wealth requires sacrifice. Rantau Heist welcomes February 2026 intakes on a dangerous mission to retrive the fortune of a lifetime. All it takes is teamwork, resillience, and of course, willingness to betray even your closest teammates. Now the question isn't whether we can get the money or not, it's what will you do to gain it?.",
      id: "Meraih kekayaan menuntut pengorbanan. Rantau Heist membuka pendaftaran untuk angkatan Februari 2026 guna menjalankan misi berbahaya demi mendapatkan harta karun seumur hidup. Kuncinya hanyalah kerja sama tim, ketangguhan, dan tentu saja, kesediaan untuk mengkhianati rekan satu tim terdekatmu sekalipun. Kini, pertanyaannya bukan lagi apakah kita bisa mendapatkan uang itu atau tidak, melainkan: apa yang akan kamu lakukan untuk mendapatkannya?",
    },
    excerpt: {
      en: "The price of wealth requires sacrifice. Rantau Heist welcomes February 2026 intakes on a dangerous mission to retrive the fortune of a lifetime.",
      id: "Meraih kekayaan menuntut pengorbanan. Rantau Heist membuka pendaftaran untuk angkatan Februari 2026 guna menjalankan misi berbahaya demi mendapatkan harta karun sekali seumur hidup.",
    },
    registrationLink: null,
    registrationDeadline: null,
    photos: "https://drive.google.com/drive/folders/1qN7mzfjQQK42_1FI1HDEgt2S9R0cQd_L",
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "survival-night-2025",
    title: "Survival Night: Game Over",
    date: "2025-11-01",
    dateDisplay: "1 Nov 2025",
    time: "4:00 PM",
    venue: "Sunway Geo Residence",
    category: "Welcome",
    status: "archived",
    poster: "/assets/photos/event_cover/survivalnight.png",
    description: {
      en: "One place. One time. Only a few will survive. Step into Survival Night: Game Over, the ultimate test of courage, strategy, and endurance. Every choice matters — will you trust, betray, or fight your way to victory? In a secret location cloaked in mystery, alliances will form, tensions will rise, and only the sharpest will outlast the game.",
      id: "Satu tempat. Satu waktu. Hanya sedikit yang akan bertahan. Masuki Survival Night: Game Over, ujian pamungkas keberanian, strategi, dan daya tahan. Setiap pilihan penting — akankah Anda mempercayai, mengkhianati, atau berjuang menuju kemenangan? Di lokasi rahasia yang diselimuti misteri, aliansi akan terbentuk, ketegangan akan meningkat, dan hanya yang paling cerdas yang akan bertahan dalam permainan ini.",
    },
    excerpt: {
      en: "One place. One time. Only a few will survive.",
      id: "Satu tempat. Satu waktu. Hanya sedikit yang akan bertahan.",
    },
    registrationLink: null,
    registrationDeadline: null,
    photos: "https://drive.google.com/drive/folders/1ZN06XnGKbzB72ouGJ42sQMj7jKx6fX9e",
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "independence-day-2025",
    title: "Independence Day 2025",
    date: "2025-08-17",
    dateDisplay: "17 Aug 2025",
    time: "3:00 PM",
    venue: "Monash University Malaysia, Sunway Campus",
    category: "Cultural",
    status: "archived",
    poster: "/assets/photos/event_cover/niskala.jpeg",
    description: {
      en: "Indonesia marked its 80th Independence Day with joy and unity, as communities gathered for lively traditional games like tarik tambang and jembatan goyang, filling the air with laughter and friendly competition. The festivities carried on with a feast of Indonesia’s diverse culinary treasures, showcasing the nation’s rich heritage. More than a commemoration, this milestone was a vibrant celebration of resilience, togetherness, and the enduring spirit of the people—Merdeka!",
      id: "Indonesia merayakan Hari Kemerdekaan ke-80 dengan sukacita dan persatuan, saat masyarakat berkumpul untuk memainkan permainan tradisional yang meriah seperti tarik tambang dan jembatan goyang, memenuhi udara dengan tawa dan persaingan yang ramah. Perayaan berlanjut dengan pesta kuliner Indonesia yang beragam, menampilkan kekayaan warisan bangsa. Lebih dari sekadar peringatan, tonggak sejarah ini merupakan perayaan yang semarak akan ketahanan, kebersamaan, dan semangat abadi rakyat—Merdeka!",
    },
    excerpt: {
      en: "Indonesia marked its 80th Independence Day with joy and unity, as communities gathered for lively traditional games.",
      id: "Indonesia merayakan Hari Kemerdekaan ke-80 dengan sukacita dan persatuan, saat masyarakat berkumpul untuk memainkan permainan tradisional yang meriah.",
    },
    registrationLink: null,
    registrationDeadline: null,
    photos: "https://drive.google.com/drive/folders/193tv9jUbT2tG_1e7eYQDaYHxSOQ5U9at",
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "one-world-2026",
    title: "Monash University Malaysia, Sunway Campus",
    date: "2026-05-09",
    dateDisplay: "9 May 2026",
    time: "9:00 AM",
    venue: "Monash Sports Centre, Sunway",
    category: "Sports",
    status: "completed",
    poster: null,
    description: {
      en: "MUISS OneWorld brought students together representing their country in four different sports — a wonderful celebration of unity through competition. PPI Monash fielded teams across futsal, badminton, basketball, and tug-of-war, finishing as one of the top three contingents overall.",
      id: "MUISS OneWorld mempertemukan mahasiswa yang mewakili negaranya dalam empat cabang olahraga berbeda — perayaan persatuan yang indah melalui kompetisi. PPI Monash menurunkan tim di futsal, bulu tangkis, basket, dan tarik tambang, dan finis sebagai salah satu dari tiga kontingen terbaik secara keseluruhan.",
    },
    excerpt: {
      en: "MUISS OneWorld brought students together representing their country in four different sports — a wonderful celebration of unity through competition.",
      id: "MUISS OneWorld mempertemukan mahasiswa yang mewakili negaranya dalam empat cabang olahraga — perayaan persatuan yang indah melalui kompetisi.",
    },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: "https://ppimonashmalaysia.com/articles/one-world-2026/",
    sponsors: [],
    organizerDept: "External Relations",
    featured: false,
  },
  {
    id: "mini-welpar-2026",
    title: "Kumpul Yuk!",
    date: "2026-08-08",
    dateDisplay: "8 Aug 2026",
    time: "5:30 PM",
    venue: "Monash University Malaysia, Sunway Campus",
    category: "Welcome",
    status: "completed",
    poster: "/assets/photos/event_cover/kumpulyuk.png",
    description: {
      en: "Come gather with us at PPI Monash Malaysia‘s Welcoming Party 2026! Dive into exciting challenges along with new friends. Kumpul yuk!",
      id: "Ayo bergabung bersama kami di Pesta Penyambutan PPI Monash Malaysia 2026! Ikuti tantangan seru bersama teman-teman baru. Kumpul yuk!",
    },
    excerpt: { 
      en: "Come gather with us at PPI Monash Malaysia's Welcome Party 2026!", 
      id: "Mari bergabung bersama kami di Pesta Penyambutan PPI Monash Malaysia 2026!" 
    },
    registrationLink: null,
    registrationDeadline: null,
    photos: "https://drive.google.com/drive/folders/10ZKQASbSqqkRVidsnHpumcBpzSWJSGcD?usp=drive_link",
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "independence-day-2026",
    title: "Independence Day",
    date: "2026-08-15",
    dateDisplay: "15 Aug 2026",
    time: null,
    venue: "To be announced",
    category: "Cultural",
    status: "upcoming",
    poster: null,
    description: {
      en: "Part of Kabinet Eunoia's Semester 2 2026 program — full details to be announced.",
      id: "Bagian dari program Kabinet Eunoia Semester 2 2026 — detail lengkap akan diumumkan.",
    },
    excerpt: { en: "Details to be announced.", id: "Detail akan diumumkan." },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: true,
  },
  {
    id: "independence-day-charity-2026",
    title: "Independence Day Charity Event",
    date: "2026-08-17",
    dateDisplay: "17–19 Aug 2026",
    time: null,
    venue: "To be announced",
    category: "Community",
    status: "upcoming",
    poster: null,
    description: {
      en: "Part of Kabinet Eunoia's Semester 2 2026 program — full details to be announced.",
      id: "Bagian dari program Kabinet Eunoia Semester 2 2026 — detail lengkap akan diumumkan.",
    },
    excerpt: { en: "Details to be announced.", id: "Detail akan diumumkan." },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "mcn-2026",
    title: "MCN",
    date: "2026-09-15",
    dateDisplay: "Tentative",
    time: null,
    venue: "To be announced",
    category: "Cultural",
    status: "upcoming",
    poster: null,
    description: {
      en: "Part of Kabinet Eunoia's Semester 2 2026 program — date tentative, details to be announced.",
      id: "Bagian dari program Kabinet Eunoia Semester 2 2026 — tanggal tentatif, detail akan diumumkan.",
    },
    excerpt: { en: "Date tentative — details to be announced.", id: "Tanggal tentatif — detail akan diumumkan." },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "welpar-october-2026",
    title: "Welpar October",
    date: "2026-10-31",
    dateDisplay: "31 Oct 2026",
    time: null,
    venue: "To be announced",
    category: "Welcome",
    status: "upcoming",
    poster: null,
    description: {
      en: "Part of Kabinet Eunoia's Semester 2 2026 program — full details to be announced.",
      id: "Bagian dari program Kabinet Eunoia Semester 2 2026 — detail lengkap akan diumumkan.",
    },
    excerpt: { en: "Details to be announced.", id: "Detail akan diumumkan." },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "makeun-2026",
    title: "Makeun",
    date: "2026-11-30",
    dateDisplay: "Monthly",
    time: null,
    venue: "To be announced",
    category: "Community",
    status: "upcoming",
    poster: null,
    description: {
      en: "A monthly community get-together — part of Kabinet Eunoia's Semester 2 2026 program. Details to be announced.",
      id: "Kumpul komunitas bulanan — bagian dari program Kabinet Eunoia Semester 2 2026. Detail akan diumumkan.",
    },
    excerpt: { en: "A monthly community get-together.", id: "Kumpul komunitas bulanan." },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "splash-mania-2025",
    title: "Splash Mania",
    date: "2025-08-09",
    dateDisplay: "9 Aug 2025",
    time: "3:00 PM",
    venue: "Monash University Malaysia, Badminton Court",
    category: "Welcome",
    status: "archived",
    poster: "/assets/photos/event_cover/splashmania.png",
    description: {
      en: "Splash Mania made a vibrant splash in welcoming the February 2025 intakes, filling the day with laughter, excitement, and water-themed fun. From energetic activities to playful moments, the event created the perfect space for newcomers to connect, break the ice, and form new friendships. More than just a welcome, Splash Mania was a celebration of togetherness, joy, and a refreshing start to the academic journey ahead.",
      id: "Splash Mania hadir dengan penuh kegembiraan dalam menyambut mahasiswa angkatan Februari 2025, mengisi hari dengan tawa, keseruan, dan permainan air. Dari aktivitas berenergi hingga momen seru, acara ini menjadi wadah sempurna bagi para mahasiswa baru untuk saling mengenal, mencairkan suasana, dan menjalin pertemanan baru. Lebih dari sekadar penyambutan, Splash Mania adalah perayaan kebersamaan, keceriaan, dan awal yang menyegarkan untuk perjalanan akademis ke depan.",
    },
    excerpt: {
      en: "Splash Mania made a vibrant splash in welcoming the February 2025 intakes, filling the day with laughter, excitement, and water-themed fun.",
      id: "Splash Mania hadir dengan penuh kegembiraan dalam menyambut mahasiswa angkatan Februari 2025, mengisi hari dengan tawa, keseruan, dan permainan air.",
    },
    registrationLink: null,
    registrationDeadline: null,
    photos: "https://drive.google.com/drive/folders/1t-OmHi0De8lllxwlUB6RLj7WOYXNtc_H?usp=sharing",
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "angkringan-2025",
    title: "Angkringan 2025",
    date: "2025-05-10",
    dateDisplay: "10 May 2025",
    time: "10:00 AM",
    venue: "Monash University Malaysia, Porch",
    category: "Cultural",
    status: "archived",
    poster: "/assets/photos/event_cover/angkringan2025.png",
    description: {
      en: "We were honored to take part in One World 2025 by proudly selling traditional delicacies and drinks. Our Angkringan booth quickly became a lively hub, with students from different backgrounds eager to try our local favorites. It was a heartwarming experience to see our heritage embraced so warmly. Angkringan wasn’t just about the food, it was about bringing people together by the spirit of our home country.",
      id: "Kami merasa terhormat dapat berpartisipasi dalam One World 2025 dengan bangga menjual makanan dan minuman tradisional. Booth Angkringan kami dengan cepat menjadi pusat keramaian, di mana mahasiswa dari berbagai latar belakang antusias mencoba hidangan favorit lokal kami. Sungguh pengalaman yang hangat melihat warisan budaya kita disambut begitu baik. Angkringan bukan hanya soal makanan, melainkan tentang menyatukan orang-orang dalam semangat tanah air.",
    },
    excerpt: {
      en: "We were honored to take part in One World 2025 by proudly selling traditional delicacies and drinks.",
      id: "Kami merasa terhormat dapat berpartisipasi dalam One World 2025 dengan bangga menjual makanan dan minuman tradisional.",
    },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "indovasion-2025",
    title: "Indovasion",
    date: "2025-03-15",
    dateDisplay: "15 Mar 2025",
    time: "4:00 PM",
    venue: "Monash University Malaysia, Badminton Court",
    category: "Welcome",
    status: "archived",
    poster: "/assets/photos/event_cover/indovasion.png",
    description: {
      en: "We warmly welcomed our February 2025 intake students with a party filled with laughter and joy. The traditional games we played brought the new and current students closer together. As the night wrapped up with a delicious dinner, new friendships were formed and lasting memories were made. But what truly mattered was the solidarity in the air throughout the event, the kind that makes you feel like you belong.",
      id: "Kami menyambut hangat mahasiswa angkatan Februari 2025 dengan pesta yang penuh tawa dan kegembiraan. Permainan tradisional yang dimainkan berhasil mempererat hubungan antara mahasiswa baru dan mahasiswa senior. Saat malam ditutup dengan santap malam bersama, pertemanan baru terbentuk dan kenangan indah tercipta. Namun yang terpenting adalah rasa solidaritas yang terjalin sepanjang acara, perasaan yang membuat Anda merasa memiliki rumah kedua.",
    },
    excerpt: {
      en: "We warmly welcomed our February 2025 intake students with a party filled with laughter and joy.",
      id: "Kami menyambut hangat mahasiswa angkatan Februari 2025 dengan pesta yang penuh tawa dan kegembiraan.",
    },
    registrationLink: null,
    registrationDeadline: null,
    photos: "https://drive.google.com/drive/folders/1d-FvgX4DRRKen2p48REwfE8cXoUBm80v?usp=drive_link",
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "murder-at-monash-academy-2024",
    title: "Murder at Monash Academy",
    date: "2024-11-02",
    dateDisplay: "2 Nov 2024",
    time: "4:00 PM",
    venue: "Monash University Malaysia, Badminton Court",
    category: "Welcome",
    status: "archived",
    poster: "/assets/photos/event_cover/murderatmonashacademy.png",
    description: {
      en: "Murder at Moonash Academy was a thrilling, spooky night to remember! With a haunting theme, chilling games, and eerie vibes, the highlight was venturing into a dark room for a suspenseful “Who Did Who” game. Laughter, screams, and surprises made it an unforgettable and spine-tingling experience for all.",
      id: "Murder at Monash Academy adalah malam penyambutan yang mendebarkan dan menyeramkan untuk dikenang! Dengan tema hantu, permainan yang menegangkan, dan suasana mistis, puncaknya adalah memasuki ruangan gelap untuk permainan 'Who Did Who' yang penuh misteri. Gelak tawa, jeritan, dan kejutan menjadikannya pengalaman yang tak terlupakan bagi semua orang.",
    },
    excerpt: {
      en: "Murder at Moonash Academy was a thrilling, spooky night to remember!",
      id: "Murder at Monash Academy adalah malam penyambutan yang mendebarkan dan menyeramkan untuk dikenang!",
    },
    registrationLink: null,
    registrationDeadline: null,
    photos: "https://drive.google.com/drive/folders/1ETg_cZOVDPXnPVzjLM7iAfLoRFHvcCU9?usp=sharing",
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "monash-cultural-night-2024",
    title: "Monash Cultural Night 2024",
    date: "2024-10-08",
    dateDisplay: "8 Oct 2024",
    time: null,
    venue: "Monash University Malaysia",
    category: "Cultural",
    status: "archived",
    poster: "/assets/photos/event_cover/monashculturalnight2024.png",
    description: {
      en: "At Monash Cultural Night, we proudly showcased Indonesian culture through a Sumatra dance, a powerful colonial-era roleplay, and performances of “Sempurna” and “Kebyar-Kebyar” by Cokelat. We celebrated tradition in Balinese attire—and won Best Cultural Presentation and Best Dressed King! An unforgettable night of pride and performance.",
      id: "Di Monash Cultural Night, kami dengan bangga memamerkan kebudayaan Indonesia melalui tarian Sumatra, teater era kolonial yang memukau, serta penampilan lagu 'Sempurna' dan 'Kebyar-Kebyar' oleh Cokelat. Kami merayakan tradisi dalam pakaian adat Bali—dan berhasil memenangkan Presentasi Budaya Terbaik serta Raja Berbusana Terbaik! Malam yang tak terlupakan penuh kebanggaan dan pertunjukan luar biasa.",
    },
    excerpt: {
      en: "At Monash Cultural Night, we proudly showcased Indonesian culture through dance, roleplay, and musical performances.",
      id: "Di Monash Cultural Night, kami dengan bangga memamerkan kebudayaan Indonesia melalui tarian, teater, dan pertunjukan musik.",
    },
    registrationLink: null,
    registrationDeadline: null,
    photos: null,
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
  {
    id: "arunika-2024",
    title: "Arunika 2024",
    date: "2024-08-17",
    dateDisplay: "17 Aug 2024",
    time: null,
    venue: "Monash University Malaysia",
    category: "Cultural",
    status: "archived",
    poster: "/assets/photos/event_cover/arunika2024.png",
    description: {
      en: "We celebrated our country’s 79th Independence Day with Arunika, an event filled with pride, laughter, and togetherness. We began with a flag ceremony, followed by a series of traditional games that brought out everyone’s energetic spirit, and ended the evening with a shared dinner. Arunika was more than just a celebration, it was a reminder of unity and the spirit that connects us as Indonesians, even away from home.",
      id: "Kami merayakan Hari Kemerdekaan ke-79 Republik Indonesia melalui Arunika, sebuah acara yang penuh kebanggaan, gelak tawa, dan kebersamaan. Kami mengawalinya dengan upacara bendera, dilanjutkan dengan serangkaian lomba tradisional yang membakar semangat, dan mengakhiri malam dengan makan malam bersama. Arunika bukan sekadar perayaan, melainkan pengingat akan persatuan dan semangat yang menghubungkan kita sebagai bangsa Indonesia, meski jauh dari tanah air.",
    },
    excerpt: {
      en: "We celebrated our country’s 79th Independence Day with Arunika, an event filled with pride, laughter, and togetherness.",
      id: "Kami merayakan Hari Kemerdekaan ke-79 Republik Indonesia melalui Arunika, sebuah acara yang penuh kebanggaan, gelak tawa, dan kebersamaan.",
    },
    registrationLink: null,
    registrationDeadline: null,
    photos: "https://drive.google.com/drive/folders/1Uy1AhJU47c3zNMpzr6rSYVPtWBblkxM9?usp=sharing",
    recapArticle: null,
    sponsors: [],
    organizerDept: "Events",
    featured: false,
  },
];
