// ============================================================================
// Part of the site content config (split from siteConfig.js).
// Re-exported by siteConfig.js — import from "../config/siteConfig" as usual.
// ============================================================================

// ─── 🏛️ Leadership History ───────────────────────────────────────────────────
// Shown on /about/history — one entry per cabinet year, newest first.
// president/vicePresident: "TBD" if not confirmed (shows "?" initials avatar)
// isFoundingYear: true only for 2017
// isCurrent: true for the active cabinet year
//
export const LEADERSHIP_HISTORY = [
  {
    year: 2026,
    cabinet: "Eunoia",
    president: "Radhitya Hendra Putra",
    vicePresident: "Nevan Elkana Hulu",
    presidentPhoto: null,
    vpPhoto: null,
    isCurrent: true,
    isFoundingYear: false,
    achievements: [
      "Launched the new PPI Monash Malaysia website",
      "Organized Rantau Heist welcome event for new intakes",
      "Hosted One World: Indonesia Hand in Hand sports competition",
      "Opened Indonesian Night Market in collaboration with other student societies",
    ],
    notes: "Cabinet Eunoia focuses on building a warm, close-knit community — welfare, collaboration, and meaningful experiences at the heart of everything.",
  },
  {
    year: 2025,
    cabinet: "Eunoia",
    president: "Victor Christopher Wahjudi Widjaja",
    vicePresident: "Mildred Shakira",
    presidentPhoto: null,
    vpPhoto: null,
    isCurrent: false,
    isFoundingYear: false,
    achievements: [
      "Indovasion",
      "Angkringan",
      "Splash Mania",
      "Independence Day 2025",
      "Survival Night: Game Over",
    ],
    notes: null,
  },
  {
    year: 2024,
    cabinet: "Eunoia",
    president: "Aidan Pramudya",
    vicePresident: "Justin Nicholas",
    presidentPhoto: null,
    vpPhoto: null,
    isCurrent: false,
    isFoundingYear: false,
    achievements: [
      "Arunika 2024",
      "Monash Cultural Night 2024",
      "Murder at Monash Academy",
    ],
    notes: null,
  },
  {
    year: 2023,
    cabinet: "Eunoia",
    president: "Melvin Loa",
    vicePresident: "Ervina Kurnia Wijaya",
    presidentPhoto: null,
    vpPhoto: null,
    isCurrent: false,
    isFoundingYear: false,
    achievements: [
      "Annual welcome program for new intakes",
      "Community welfare initiatives and cultural programs",
    ],
    notes: null,
  },
  {
    year: 2022,
    cabinet: "Eunoia",
    president: "Alfredo Waldemar Sinaga",
    vicePresident: "Enzo Brooklyn",
    presidentPhoto: null,
    vpPhoto: null,
    isCurrent: false,
    isFoundingYear: false,
    achievements: [
      "Resumed in-person events following COVID-19 restrictions",
      "Strengthened collaboration with other student societies on campus",
    ],
    notes: null,
  },
  {
    year: 2021,
    cabinet: "Eunoia",
    president: "Kenanga Pramitha",
    vicePresident: "Tuanku Muhammad Rabbany Syahidullah Narukaya",
    presidentPhoto: null,
    vpPhoto: null,
    isCurrent: false,
    isFoundingYear: false,
    achievements: [
      "Adapted activities to hybrid and online formats",
      "Maintained community connection through virtual events and welfare check-ins",
    ],
    notes: null,
  },
  {
    year: 2020,
    cabinet: "Eunoia",
    president: "Amanda Silmy",
    vicePresident: "Muarif Surya Laksono",
    presidentPhoto: null,
    vpPhoto: null,
    isCurrent: false,
    isFoundingYear: false,
    achievements: [
      "Navigated the challenges of the COVID-19 pandemic",
      "Pivoted to online community support for students stranded abroad",
    ],
    notes: null,
  },
  {
    year: 2019,
    cabinet: "Eunoia",
    president: "Reza Auditya Wijaya",
    vicePresident: "Jessie Mettaurine",
    presidentPhoto: null,
    vpPhoto: null,
    isCurrent: false,
    isFoundingYear: false,
    achievements: [
      "Expanded event calendar with sports and cultural programs",
      "Grew external partnerships with other Indonesian student bodies in Malaysia",
    ],
    notes: null,
  },
  {
    year: 2018,
    cabinet: "Eunoia",
    president: "Satria Wardhana Sarosa",
    vicePresident: "Richard Liking",
    presidentPhoto: null,
    vpPhoto: null,
    isCurrent: false,
    isFoundingYear: false,
    achievements: [
      "Formalized departmental structure across six departments",
      "Grew membership significantly in the second year of operation",
    ],
    notes: null,
  },
  {
    year: 2017,
    cabinet: "Founding Committee",
    president: "Satria Wardhana Sarosa",
    vicePresident: "Richard Liking",
    presidentPhoto: null,
    vpPhoto: null,
    isCurrent: false,
    isFoundingYear: true,
    achievements: [
      "Founded PPI Monash Malaysia in August 2017",
      "Established six founding departments",
      "Held the first welcome event for Indonesian students at Monash",
    ],
    notes: "PPI Monash Malaysia was officially established as a branch of PPIM (Perhimpunan Pelajar Indonesia se-Malaysia), with the mission of supporting Indonesian students at Monash University Malaysia.",
  },
];
