// ============================================================================
// Part of the site content config (split from siteConfig.js).
// Re-exported by siteConfig.js — import from "../config/siteConfig" as usual.
// ============================================================================

// ─── 🤝 Partners ─────────────────────────────────────────────────────────────
// Partners, sponsors, and institutional collaborators shown on /collaboration.
//
// Categories: "Institutional Partner" | "University Partner" |
// "Embassy / Government" | "Student Organization" | "Media Partner" |
// "Event Sponsor" | "Corporate Sponsor" | "Community Partner"
//
// active: false  → archived past partner; shown in the "View archive" section
// displayOrder   → lower = shown first in the partner grid
//
export const PARTNERS = [
  {
    id: "kbri-kuala-lumpur",
    name: "KBRI Kuala Lumpur",
    logo: null,
    category: "Embassy / Government",
    website: "https://kbrikualalumpur.org/",
    socialUrl: null,
    description: "The Embassy of the Republic of Indonesia in Kuala Lumpur — our official institutional partner for student support, consular services, and cultural programs.",
    active: true,
    displayOrder: 1,
    partnershipSince: "2017",
    relatedEventIds: [],
  },
  {
    id: "ppim",
    name: "PPIM",
    logo: null,
    category: "Institutional Partner",
    website: "https://ppimalaysia.org/",
    socialUrl: "https://instagram.com/ppimalaysia",
    description: "Perhimpunan Pelajar Indonesia se-Malaysia — the national umbrella body coordinating all PPI branches across Malaysia. PPI Monash is a proud member branch.",
    active: true,
    displayOrder: 2,
    partnershipSince: "2017",
    relatedEventIds: [],
  },
  {
    id: "monash-malaysia",
    name: "Monash University Malaysia",
    logo: null,
    category: "University Partner",
    website: "https://www.monash.edu.my/",
    socialUrl: "https://instagram.com/monashmalaysia",
    description: "Our home campus. Monash University Malaysia recognises PPI Monash as an officially registered student organisation and supports our activities on campus.",
    active: true,
    displayOrder: 3,
    partnershipSince: "2017",
    relatedEventIds: [],
  },
  {
    id: "ppi-jerman",
    name: "PPI Jerman",
    logo: null,
    category: "Student Organization",
    website: "https://www.ppijerman.org/",
    socialUrl: "https://instagram.com/ppijerman",
    description: "Perhimpunan Pelajar Indonesia di Jerman — a fellow PPI branch representing Indonesian students across Germany. Our international collaboration partner for webinars and cross-country exchange programs.",
    active: true,
    displayOrder: 4,
    partnershipSince: "2026",
    relatedEventIds: [],
  },
  {
    id: "muiss",
    name: "MUISS",
    logo: null,
    category: "Student Organization",
    website: null,
    socialUrl: "https://instagram.com/muiss_official",
    description: "Monash University International Students Society — our on-campus partner for multicultural events including the annual OneWorld sports competition.",
    active: true,
    displayOrder: 5,
    partnershipSince: "2023",
    relatedEventIds: ["one-world-2026"],
  },
  {
    id: "monash-mss",
    name: "Monash Malaysian Students' Society",
    logo: null,
    category: "Student Organization",
    website: null,
    socialUrl: null,
    description: "A frequent on-campus collaborator for joint cultural and community events, including the Indonesian Night Market.",
    active: true,
    displayOrder: 6,
    partnershipSince: "2024",
    relatedEventIds: ["indonesian-night-market-2026"],
  },
  {
    id: "monash-india",
    name: "Monash Indian Students' Association",
    logo: null,
    category: "Student Organization",
    website: null,
    socialUrl: null,
    description: "A collaborating campus student society for joint cultural programs and campus events.",
    active: true,
    displayOrder: 7,
    partnershipSince: "2025",
    relatedEventIds: ["indonesian-night-market-2026"],
  },
  // Past / inactive partners — shown in the archive section on /collaboration
  {
    id: "sunway-pyramid",
    name: "Sunway Pyramid Mall",
    logo: null,
    category: "Event Sponsor",
    website: "https://www.sunwaypyramid.com/",
    socialUrl: null,
    description: "Venue and logistical sponsor for the 2024 Merdeka Charity Run, providing the boulevard route and on-site event support.",
    active: false,
    displayOrder: 10,
    partnershipSince: null,
    relatedEventIds: ["merdeka-run-2024"],
  },
  {
    id: "tba-corporate-sponsor",
    name: "TBA — Corporate Sponsor",
    logo: null,
    category: "Corporate Sponsor",
    website: null,
    socialUrl: null,
    description: "Placeholder — replace with the actual corporate sponsor name. Contact External Relations to discuss sponsorship opportunities.",
    active: false,
    displayOrder: 11,
    partnershipSince: null,
    relatedEventIds: [],
  },
  {
    id: "tba-media-partner",
    name: "TBA — Media Partner",
    logo: null,
    category: "Media Partner",
    website: null,
    socialUrl: null,
    description: "Placeholder — replace with the actual media partner. Contact External Relations if you have a media collaboration to propose.",
    active: false,
    displayOrder: 12,
    partnershipSince: null,
    relatedEventIds: [],
  },
];

// ─── 🌐 Collaborations ───────────────────────────────────────────────────────
// Records of specific joint programs, events, and exchanges.
// Each entry references a PARTNERS id via partnerId.
//
// Types: "International Collaboration" | "PPI Malaysia Joint Event" |
// "Sponsorship Partnership" | "Institutional Program" |
// "Media Collaboration" | "Article Exchange" | "Cultural Exchange" |
// "Academic Webinar"
//
// status: "upcoming" | "ongoing" | "completed" | "archived"
// featured: true → shown in the hub page spotlight section
//
export const COLLABORATIONS = [
  {
    id: "ppi-jerman-webinar-2026",
    title: "Studying Abroad: PPI Monash x PPI Jerman Webinar",
    partnerId: "ppi-jerman",
    type: "International Collaboration",
    date: "2026-04-20",
    dateDisplay: "20 Apr 2026",
    description: "A joint online webinar where Indonesian students in Malaysia and Germany shared their study-abroad experiences, scholarship tips, and cultural adjustment stories.",
    relatedEventId: null,
    relatedArticleId: null,
    mediaUrl: null,
    photos: null,
    status: "completed",
    featured: true,
  },
  {
    id: "ppim-independence-day-2025",
    title: "PPIM Independence Day Program 2025",
    partnerId: "ppim",
    type: "PPI Malaysia Joint Event",
    date: "2025-08-17",
    dateDisplay: "17 Aug 2025",
    description: "A nationally coordinated Independence Day program across all PPI Malaysia branches. PPI Monash hosted the Sunway leg, contributing cultural performances and a flag ceremony.",
    relatedEventId: "independence-day-2025",
    relatedArticleId: "merdeka-spirit-on-campus-2025",
    mediaUrl: null,
    photos: null,
    status: "completed",
    featured: false,
  },
  {
    id: "kbri-cultural-program-2026",
    title: "KBRI Indonesian Cultural Outreach Program",
    partnerId: "kbri-kuala-lumpur",
    type: "Institutional Program",
    date: "2026-07-01",
    dateDisplay: "Jul 2026",
    description: "An ongoing cultural outreach program co-facilitated with KBRI Kuala Lumpur, providing Indonesian students with consular services, cultural guidance, and community touchpoints throughout the academic year.",
    relatedEventId: null,
    relatedArticleId: null,
    mediaUrl: null,
    photos: null,
    status: "ongoing",
    featured: true,
  },
  {
    id: "muiss-one-world-2026",
    title: "MUISS OneWorld 2026",
    partnerId: "muiss",
    type: "Cultural Exchange",
    date: "2026-05-09",
    dateDisplay: "9 May 2026",
    description: "PPI Monash participated as the Indonesian contingent in MUISS OneWorld — a multi-sport multicultural event at Monash Sunway campus. Finished third overall across four sports.",
    relatedEventId: "one-world-2026",
    relatedArticleId: "one-world-2026",
    mediaUrl: null,
    photos: null,
    status: "completed",
    featured: false,
  },
  {
    id: "night-market-collab-2026",
    title: "Indonesian Night Market",
    partnerId: "monash-mss",
    type: "PPI Malaysia Joint Event",
    date: "2026-08-23",
    dateDisplay: "23 Aug 2026",
    description: "A street-food-style night market on campus, co-organized with Monash Malaysian Students' Society and Monash Indian Students' Association. Indonesian, Malaysian, and Indian stalls alongside live acoustic performances.",
    relatedEventId: "indonesian-night-market-2026",
    relatedArticleId: null,
    mediaUrl: null,
    photos: null,
    status: "upcoming",
    featured: true,
  },
  {
    id: "ppi-jerman-article-exchange-2027",
    title: "PPI Monash x PPI Jerman Article Exchange",
    partnerId: "ppi-jerman",
    type: "Article Exchange",
    date: "2027-01-01",
    dateDisplay: "Early 2027",
    description: "A planned cross-platform article exchange where PPI Monash and PPI Jerman contributors share student experience stories across each other's platforms.",
    relatedEventId: null,
    relatedArticleId: null,
    mediaUrl: null,
    photos: null,
    status: "upcoming",
    featured: false,
  },
];

// ─── 🇲🇾 PPI Malaysia Network ────────────────────────────────────────────────
// Directory of Indonesian student associations across Malaysian universities,
// shown on the /network page.
//
// collaborationStatus: "active" | "occasional" | "none"
//
// NOTE TO COMMITTEE: The Instagram URLs below follow a placeholder pattern
// (instagram.com/ppi_[campus]). Please verify and replace each one with the
// actual official handle before going live. Contact PPIM for the full
// branch directory and correct social links.
//
export const PPI_NETWORK = [
  {
    id: "ppi-taylors",
    name: "PPI Taylor's University",
    city: "Subang Jaya",
    university: "Taylor's University",
    logo: null,
    website: null,
    socialUrl: "https://instagram.com/ppi_taylors",
    collaborationStatus: "active",
    description: "Indonesian student community at Taylor's University — a neighbour campus and frequent collaborator for joint events across Subang Jaya.",
  },
  {
    id: "ppi-sunway",
    name: "PPI Sunway University",
    city: "Subang Jaya",
    university: "Sunway University",
    logo: null,
    website: null,
    socialUrl: "https://instagram.com/ppi_sunwayuniversity",
    collaborationStatus: "active",
    description: "Indonesian students at Sunway University — a natural collaborator given the shared Bandar Sunway location.",
  },
  {
    id: "ppi-upm",
    name: "PPI UPM",
    city: "Serdang",
    university: "Universiti Putra Malaysia",
    logo: null,
    website: null,
    socialUrl: "https://instagram.com/ppi_upm",
    collaborationStatus: "active",
    description: "One of the largest PPI branches in Malaysia, based at Universiti Putra Malaysia in Serdang.",
  },
  {
    id: "ppi-um",
    name: "PPI UM",
    city: "Kuala Lumpur",
    university: "Universiti Malaya",
    logo: null,
    website: null,
    socialUrl: "https://instagram.com/ppi_um",
    collaborationStatus: "active",
    description: "PPI branch at Universiti Malaya — the oldest and one of the most prominent universities in Malaysia.",
  },
  {
    id: "ppi-nottingham",
    name: "PPI Nottingham Malaysia",
    city: "Semenyih",
    university: "University of Nottingham Malaysia",
    logo: null,
    website: null,
    socialUrl: "https://instagram.com/ppi_nottingham_malaysia",
    collaborationStatus: "active",
    description: "Indonesian student association at the University of Nottingham Malaysia Campus in Semenyih.",
  },
  {
    id: "ppi-ucsi",
    name: "PPI UCSI University",
    city: "Kuala Lumpur",
    university: "UCSI University",
    logo: null,
    website: null,
    socialUrl: "https://instagram.com/ppi_ucsi",
    collaborationStatus: "occasional",
    description: "Indonesian student association at UCSI University, Kuala Lumpur.",
  },
  {
    id: "ppi-help",
    name: "PPI HELP University",
    city: "Kuala Lumpur",
    university: "HELP University",
    logo: null,
    website: null,
    socialUrl: "https://instagram.com/ppi_help",
    collaborationStatus: "occasional",
    description: "Indonesian student community at HELP University, Kuala Lumpur.",
  },
  {
    id: "ppi-mmu",
    name: "PPI MMU",
    city: "Cyberjaya",
    university: "Multimedia University",
    logo: null,
    website: null,
    socialUrl: "https://instagram.com/ppi_mmu",
    collaborationStatus: "occasional",
    description: "Indonesian student community at Multimedia University (MMU), Cyberjaya.",
  },
  {
    id: "ppi-inti",
    name: "PPI INTI",
    city: "Nilai",
    university: "INTI International University",
    logo: null,
    website: null,
    socialUrl: "https://instagram.com/ppi_inti",
    collaborationStatus: "occasional",
    description: "Indonesian student association at INTI International University, Nilai.",
  },
  {
    id: "ppi-apu",
    name: "PPI APU",
    city: "Kuala Lumpur",
    university: "Asia Pacific University",
    logo: null,
    website: null,
    socialUrl: "https://instagram.com/ppi_apu",
    collaborationStatus: "occasional",
    description: "Indonesian student community at Asia Pacific University (APU), Bukit Jalil.",
  },
  {
    id: "ppi-utp",
    name: "PPI UTP",
    city: "Tronoh, Perak",
    university: "Universiti Teknologi PETRONAS",
    logo: null,
    website: null,
    socialUrl: "https://instagram.com/ppi_utp",
    collaborationStatus: "occasional",
    description: "Indonesian student community at UTP (Universiti Teknologi PETRONAS) in Perak.",
  },
  {
    id: "ppi-curtin",
    name: "PPI Curtin Malaysia",
    city: "Miri, Sarawak",
    university: "Curtin University Malaysia",
    logo: null,
    website: null,
    socialUrl: "https://instagram.com/ppi_curtinmalaysia",
    collaborationStatus: "occasional",
    description: "PPI branch at Curtin University Malaysia in Miri, Sarawak.",
  },
];
